apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - image: mecit35/mern-project-frontend
          name: frontend
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend
  
spec:
  selector:
    name: frontend
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
  