apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: 'bWVjaXQ='
  MONGO_INITDB_ROOT_PASSWORD: 'bW9uZ28xMjM='
  MONGO_URI: 'bW9uZ29kYjovL21lY2l0Om1vbmdvMTIzQG1vbmdvLXNlcnZpY2U6MjcwMTcvcGhvbmVib29rP2F1dGhTb3VyY2U9YWRtaW4='
  MONGO_INITDB_DATABASE: 'cGhvbmVib29r'
 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  FRONTEND_URL: 'http://54.175.35.178:30002'   #<worker_node_public_ip:30002>


