apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: 'bWVjaXQ='
  MONGO_INITDB_ROOT_PASSWORD: 'bW9uZ28xMjM='
  MONGO_URI: 'bW9uZ29kYjovL21lY2l0Om1vbmdvMTIzQG1vbmdvLXNlcnZpY2U6MjcwMTcvcGhvbmVib29rP2F1dGhTb3VyY2U9YWRtaW4='
  MONGO_INITDB_DATABASE: 'cGhvbmVib29r'


