apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/myvolume"
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi